apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daimyo-redis
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
      - name: daimyo-redis
        image: redis
        tty: true
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: daimyo-redis-service
spec:
  selector:
    service: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379